apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: benchmarking-go-redis-memcached
  description: Repository for benchmarking golang redis memcached
  labels:
    example.com/custom: custom_label_value
  annotations:
    example.com/service-discovery: artistweb
    circleci.com/project-slug: github/example-org/artist-website
  tags:
    - go
  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: website
  lifecycle: production
  owner: first-monorepo
  system: alif-portal
  dependsOn:
    - resource:default/alif-db
  dependencyOf:
    - component:default/alif-web-lookup